### ISSUE TITLE
Statische Palette und Malen durch Mausklick

### ISSUE THREAD

**Issue by HaSa1002** [BenediktMagnus/Karopapier#1]
Wenn wir die Palette statisch irgendwo zum Beispiel oben platzieren würden, dann könnte man quasi ein Malen ermöglichen, zum Beispiel Paint.
Die Malreihenfolge wäre dann:
1. Selektieren, des Objekts
2. Maus drücken (links) und gedrückt halten
3. Maus bewegen, dabei malt man

Vielleicht kann man das auch anpassen, z.B. über Settings

**Comment by LordJimBeam** [comment]
Das ist leider nicht ganz einfach zu implementieren.
Ob die Maustaste immer noch gedrückt ist kann man nicht herausfinden außer man merkt sich wann Maus runtergedrückt und wieder losgelassen wurde. Das führt aber zu allerlei Problemen wenn der Browser versucht selbstständig Drag&Drop zu machen.
Außerdem hat man keine Möglichkeit zu wissen was passiert wenn der Mauszeiger das Browser-Window verlässt. 

Ich habe die Palette trotzdem einmal (zusätzlich) links am Rand verfügbar gemacht, dann kann man einmal ein Werkzeug auswählen und mehrere Zellen hintereinander anklicken (siehe #4).

**Comment by BenediktMagnus** [comment]
Zumal sich dann die Frage stellt, ob Herumgespamme über die ganze Karte damit nicht zu einfach gemacht werden würde.
Im Entwicklungszweig ist es erstmal drin und bleibt so erhalten. Vor dem Einsetzen ins Produktivsystem müssten wir derartige Fragen aber ersteinmal klären.

**Comment by BenediktMagnus** [comment]
In der neuen Version des Karopapiers ist die Palette statisch. Sie funktioniert allerdings ein bisschen anders.
Die neue Palette ist immer zu sehen und befindet sich rechts neben der Tabelle. Sie enthält neben allen wählbaren Inhalten auch Angaben zur Häufigkeit deren Auswahl durch die Nutzer (rechts neben jedem Inhalt befindet sich ein Zähler, der angibt, wie oft dieses ausgewählt worden ist). Auf dem Feld zu sehen ist derjenige Inhalt mit den meisten Stimmen.
Wenn man ein Feld auswählt, wird die Palette mit den dazugehörigen Informationen gefüllt und man kann auf einen Inhalt klicken, um ihn auszuwählen.
Ein "Bemalen" der Tabelle ist nicht vorgesehen. Zum Einen sehe ich nicht den Anwendungsfall, da jedes einzelne Feld genau überlegt sein muss, zum Anderen würde dies Missbrauch vereinfachen.

Daher sehe ich dieses Thema als abgeschlossen an.
