### ISSUE TITLE
jQuery benutzen

### ISSUE THREAD

**Issue by LordJimBeam** [BenediktMagnus/Karopapier#5]
Ich denke nicht dass das Projekt zu klein für jQuery ist. Es ist sicherlich zu klein um irgendein vollständiges Framework wie Angular, React oder Ember zu verwenden. Aber jQuery bringt dir eine kleine Toolbox an Kram der dir die Arbeit erleichtern kann. Beispiele dafür bzw. wie man das dann in Plain JS macht sind unter 
http://youmightnotneedjquery.com/ zu finden.

Vielleicht liegt es auch an der Herangehensweise, aber ich mache viele visual changes indem ich Klassen an Elemente hänge und wieder wegnehme, und allein dafür ist es einfach viel aufgeräumter:
```js
$(el).addClass(className);
```
vs.
```js
if(el.classList)
  el.classList.add(className);
else
  el.className += ' ' + className;
```
Klasse entfernen analog. Außerdem ist es deutlich Robuster als Plain JS was verschiedene Browser-Verhalten angeht. Das ist mir persönlich die 68KB extra (die in vielen Fällen vom Browser sowieso schon gecached sind) wert.

Natürlich ist das nicht lebensnotwendig und ich würde gern Argumente dagegen hören.

**Comment by BenediktMagnus** [comment]
Ich schließe das mal.

Ich wollte immer wieder Argumente sammeln, wieso JQuery nicht (mehr) sinnvoll ist und habe sogar einen längeren Text vorbereitet, aber die Wahreit ist: Das Projekt kam in der Zeit gut ohne aus und insbesondere nach der großen Aufräumaktion und der Umstellung auf Typescript sehe ich keinen Nutzen. Das Frontend ist nicht mehr dreckig zusammengewürfelt sondern ordentlich strukturiert, was dank der Entwicklung von ECMAScript und Ereignissen wie des Wegfalls der IE/Edge-JS-Engine einfach von der Hand gegangen ist.

Um noch auf dein Beispiel einzugehen, heute genügt ein einfaches:
```javascript
element.classList.add(className);
```
Das entspricht der JQuery-Variante und kommt ohne den Wrapper aus.
