### ISSUE TITLE
Minifying mit echten Buildprozess

### ISSUE THREAD

**Issue by LordJimBeam** [BenediktMagnus/Karopapier#6]
Auch wenn das Minifying jetzt automatisch passiert wenn man die Applikation startet halte ich es doch für schlechten Stil das zu tun. Dadurch sind Runtime-Dependencies nötig die auch bequem Dev-Dependencies sein könnten (clean-css, html-minifier, uglify-es). Die Alternative wäre es einen Buildprozess mit Grunt/Gulp/Webpack/Rollup/etc. aufzusetzen und den "Build" komplett außerhalb der Applikation zu haben. scripts/Kompressor.js könnte dann weg und der selbe Effekt wäre durch eine einfache JSON-Datei erzielt anstatt 150 LOC dafür zu haben die man dann auch noch warten muss.

**Comment by BenediktMagnus** [comment]
Durch den Umstieg auf Typescript sind die Buildskripte obsolet geworden. Ich habe mich darüber hinaus dazu entschieden, (bis auf Weiteres) kein Minifying durchzuführen. Daher besteht der Buildprozess aktuell aus dem Kompilieren von Typescript.
