### ISSUE TITLE
WebSocket Messages sollten in jedem Fall das gleiche Verhalten zeigen

### ISSUE THREAD

**Issue by LordJimBeam** [BenediktMagnus/Karopapier#7]
Was ich meine ist dass eine Message die potentiell eine Antwort geben könnte das auch immer tun sollte:
```js
    socket.on('KarteHolen', function (KarteGeben)
        {
            let Karte = socket.Karte;
            if (Karte == undefined) return;
            
            KarteGeben(KarteSerialisieren(Karte));
        }
    );
```
Wenn vorher kein KarteSetzen aufgerufen wurde (durch Programmierfehler o.Ä.) oder eine Karte angefragt wurde die nicht existiert dann kommt da einfach gar nichts zurück. Das macht es schwierig zu entscheiden ob der Server einfach lange braucht zum Antworten oder ein Fehler aufgetreten ist.

**Comment by BenediktMagnus** [comment]
Das ist wahr. Das ist einer dieser Altlasten, die vom Gedanken kamen "ich mache mal eben eine kleine Karte, damit Andi morgen was Cooles im Stream hat".
Es gibt da ein paar Unsauberkeiten. Und dieser hier ist definitv eine, die bei einem vollständigen Projekt, wie es durch die Offenlegung des Quelltextes angestrebt wird, definitiv verbessert werden sollte.

**Comment by BenediktMagnus** [comment]
Am sinnvollsten wäre es wohl, in diesem Falle ein leeres Kartenarray zurückzugeben.
Sauberer wäre nur ein Fehlerprotokoll, das bei falschen Vorgaben informiert. Das würde ich aber (noch) nicht angehen, das Projekt stellt immerhin keine API dar, an die sich andere Clientimplementierungen richten könnten.

**Comment by BenediktMagnus** [comment]
Die neue Version des Karopapiers hat das nun sauber umgesetzt. Es wird in jedem Fall entweder der Callback aufgerufen (sofern einer vorhanden ist) oder im Fehlerfalle ein Fehlerereignis übermittelt, das Informationen über den Fehler beinhaltet. Aktuell umfasst das den Grund des Fehlers und das aufgerufenen Ereignis; bei Bedarf könnte dies jedoch um weitere Informationen erweitert werden.
